/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   polymer-legacy.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

import {LegacyElementMixin} from './lib/legacy/legacy-element-mixin.js';

export {Polymer} from './lib/legacy/polymer-fn.js';

export {html} from './lib/utils/html-tag.js';
