/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   gulpfile.js
 */

declare class BackfillStream {
  _transform(file: any, enc: any, cb: any): any;
  _flush(cb: any): any;
}

declare class AddClosureTypeImport {
  _transform(file: any, enc: any, cb: any): any;
}
