/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   polymer-element.html
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

/// <reference path="lib/mixins/element-mixin.d.ts" />
/// <reference path="lib/utils/html-tag.d.ts" />

declare namespace Polymer {

  /**
   * Base class that provides the core API for Polymer's meta-programming
   * features including template stamping, data-binding, attribute deserialization,
   * and property change observation.
   */
  class Element extends
    Polymer.ElementMixin(
    HTMLElement) {
  }
}
