/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   lib/utils/html-tag.html
 */

/// <reference path="boot.d.ts" />

declare namespace Polymer {


  /**
   * A template literal tag that creates an HTML <template> element from the contents of the string.
   *
   * This allows you to write a Polymer Template in JavaScript.
   *
   * Interpolated values are converted to strings when the template is created,
   * they are not intended as a replacement for Polymer data-binding.
   *
   * There is special support for HTMLTemplateElement values,
   * allowing for easy composition of superclass or partial templates.
   *
   * Example:
   *
   *   static get template() {
   *     return Polymer.html`
   *       <style>:host{ content:"..." }</style>
   *       <div class="shadowed">${this.partialTemplate}</div>
   *       ${super.template}
   *     `;
   *   }
   *   static get partialTemplate() { return Polymer.html`<span>Partial!</span>`; }
   *
   * @returns Constructed HTMLTemplateElement
   */
  function html(strings: TemplateStringsArray, ...values: any[]): HTMLTemplateElement;
}
