/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   lib/utils/perf-tester.js
 */

declare class PerfTester extends Polymer.Element {
  tests: any;
  chart: any;
  chartmin: any;
  chartmax: any;
  _strategies: object|null;
  connectedCallback(): any;
  attributeChangedCallback(name: any, old: any, value: any): any;
  _shuffle(tests: any): any;
  _go(): any;
  _startRun(): any;
  _nextTest(): any;
  _load(): any;
  _measure(next: any): any;
  _scoreMessage(e: any): any;
  _record(info: any): any;
  _report(): any;
  _drawCharts(): any;
  _calcScores(times: any, baseline: any): any;
  _stats(a: any, kind: any): any;
}

interface HTMLElementTagNameMap {
  "perf-tester": PerfTester;
}
