module.exports = function(karma) {
  var common = require('../../tools/test/karma-common.conf.js');
  karma.set(common.mixin_common_opts(karma, {
    // base path, that will be used to resolve files and exclude
    basePath: '../../',

    // list of files / patterns to load in the browser
    files: [
      'tools/test/mocha-htmltest.js',
      'polymer-dev/conf/mocha.conf.js',
      'polymer-dev/node_modules/chai/chai.js',
			'platform/platform.js',
			'polymer-dev/src/polymer.js',
			'polymer-dev/src/boot.js',
			'polymer-dev/src/lib/lang.js',
			'polymer-dev/src/lib/job.js',
			'polymer-dev/src/lib/dom.js',
			'polymer-dev/src/lib/super.js',
			'polymer-dev/src/lib/deserialize.js',
			'polymer-dev/src/api.js',
			'polymer-dev/src/instance/utils.js',
			'polymer-dev/src/instance/events.js',
			'polymer-dev/src/instance/attributes.js',
			'polymer-dev/src/instance/properties.js',
			'polymer-dev/src/instance/mdv.js',
			'polymer-dev/src/instance/base.js',
			'polymer-dev/src/instance/styles.js',
			'polymer-dev/src/declaration/path.js',
			'polymer-dev/src/declaration/styles.js',
			'polymer-dev/src/declaration/events.js',
			'polymer-dev/src/declaration/properties.js',
			'polymer-dev/src/declaration/attributes.js',
			'polymer-dev/src/declaration/prototype.js',
			'polymer-dev/src/declaration/polymer-element.js',
      'polymer-dev/test/js/*.js',
      {pattern: 'CustomElements/custom-elements.js', included: false},
      {pattern: 'CustomElements/src/*.js', included: false},
      {pattern: 'HTMLImports/html-imports.js', included: false},
      {pattern: 'HTMLImports/src/*', included: false},
      {pattern: 'MutationObservers/*.js', included: false},
      {pattern: 'NodeBind/src/*.js', included: false},
      {pattern: 'PointerEvents/pointerevents.js', included: false},
      {pattern: 'PointerEvents/src/*.js', included: false},
      {pattern: 'PointerGestures/pointergestures.js', included: false},
      {pattern: 'PointerGestures/src/*.js', included: false},
      {pattern: 'ShadowDOM/shadowdom.js', included: false},
      {pattern: 'ShadowDOM/src/**/*.js', included: false},
      {pattern: 'TemplateBinding/load.js', included: false},
      {pattern: 'TemplateBinding/src/*.css', included: false},
      {pattern: 'TemplateBinding/src/*.js', included: false},
      {pattern: 'WeakMap/weakmap.js', included: false},
      {pattern: 'observe-js/src/*.js', included: false},
      {pattern: 'observe-js/util/*.js', included: false},
      {pattern: 'platform/*.js', included: false},
      {pattern: 'platform/platform.*', included: false},
      {pattern: 'platform/src/*.js', included: false},
      {pattern: 'platform/test/**/*.html', included: false},
      {pattern: 'platform/test/**/*.js', included: false},
      {pattern: 'platform/tools/**/*.js', included: false},
      {pattern: 'polymer-expressions/src/*.js', included: false},
      {pattern: 'polymer-expressions/third_party/**/*.js', included: false},
      {pattern: 'polymer-dev/polymer.html', included: false},
      {pattern: 'polymer-dev/src/**/*.js', included: false},
      {pattern: 'polymer-dev/test/**/*.css', included: false},
      {pattern: 'polymer-dev/test/**/*.html', included: false},
      {pattern: 'polymer-dev/test/**/*.js', included: false},
      {pattern: 'tools/**/*.js', included: false}
    ]
  }));
};
