/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   lib/utils/hide-template-controls.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

export {hideElementsGlobally};


/**
 * @returns True if elements will be hidden globally
 */
declare function hideElementsGlobally(): boolean;
