/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   lib/utils/telemetry.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

export {incrementInstanceCount};

declare function incrementInstanceCount(): void;

export {register};


/**
 * Registers a class prototype for telemetry purposes.
 */
declare function register(prototype: PolymerElementConstructor): void;

export {dumpRegistrations};


/**
 * Logs all elements registered with an `is` to the console.
 */
declare function dumpRegistrations(): void;

import {PolymerElementConstructor} from '../../interfaces';
