/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   lib/legacy/legacy-data-mixin.html
 */

/// <reference path="class.d.ts" />
/// <reference path="../utils/mixin.d.ts" />

declare class UndefinedArgumentError {
  constructor(message: any);
}

declare class LegacyDataMixin {

  /**
   * Overrides `Polyer.PropertyEffects` to wrap effect functions to
   * catch `UndefinedArgumentError`s and warn.
   *
   * @param property Property that should trigger the effect
   * @param type Effect type, from this.PROPERTY_EFFECT_TYPES
   * @param effect Effect metadata object
   */
  _addPropertyEffect(property: string, type: string, effect?: object|null): void;
}
