/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   util/minimalDocument.js
 */

declare class MinimalDocTransform {
  _transform(file: any, enc: any, cb: any): any;
}
